package net.schueller.peertube.feature_video.domain.model

import android.os.Parcelable
import java.util.*

data class Video(
    val account: Account?,
    val blacklisted:  Boolean?,
    val blacklistedReason: String?,
    val category: Category?,
    val channel: Channel?,
    val commentsEnabled:  Boolean,
    val createdAt: Date?,
    val description: String?,
    val descriptionPath: String?,
    val dislikes: Int,
    val downloadEnabled:  Boolean,
    val duration: Int,
    val embedPath: String?,
    val files: List<File>?,
    val id: Int,
    val isLive:  Boolean,
    val isLocal:  Boolean,
    val language: Language?,
    val licence: Licence?,
    val likes: Int,
    val name: String?,
    val nsfw: Boolean,
    val originallyPublishedAt: Date?,
    val previewPath: String?,
    val privacy: Privacy?,
    val publishedAt: Date?,
    val scheduledUpdate: ScheduledUpdate?,
    val shortUUID: String?,
    val state: State?,
    val streamingPlaylists: List<SteamingPlaylist>?,
    val support: String?,
    val tags: List<String>?,
    val thumbnailPath: String?,
    val trackerUrls: List<String>?,
    val updatedAt: Date?,
    val userHistory: UserHistory?,
    val uuid: String,
    val views: Int,
    val waitTranscoding:  Boolean?,
)